name: BuildCRMLite

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        id: build
        run: |
          mkdir -p $GITHUB_WORKSPACE/CRMLiteBUILD
          echo ::set-output name=version::${GITHUB_REF:10}
          echo ::set-output name=path::$GITHUB_WORKSPACE/CRMLite
          # Copia de archivos del repositorio a la carpeta CRMLite
          cp -a $GITHUB_WORKSPACE/CRMLite $GITHUB_WORKSPACE/CRMLiteBUILD/
          # Comprimimos la carpeta CRMLite en .zip
          zip -9 -r CRMLite${GITHUB_REF:10}.zip CRMLiteBUILD
          cp CRMLite${GITHUB_REF:10}.zip CRMLiteBUILD
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CRMLite${{ steps.build.outputs.version }}.zip
          asset_name: CRMLite${{ steps.build.outputs.version }}.zip
          tag: ${{ github.ref }}
          overwrite: true
